name: Auto Push on Master

on:
  push:
    branches:
      - master

jobs:
  auto-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # use your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      # Example: Push built files to another branch or folder
      - name: Commit and Push Build (Optional)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto build push from GitHub Actions" || echo "No changes to commit"
          git push origin master
